
        SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K0' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K1' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K2' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K3' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K4' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K5' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K6' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K7' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K8' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K9' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K10' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K11' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K12' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K13' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K14' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K15' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K16' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K17' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K18' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K19' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K20' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K21' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K22' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K23' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K24' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K25' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K26' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K27' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K28' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K29' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K30' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K31' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K32' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K33' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K34' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K35' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K36' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K37' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K38' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K39' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K40' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K41' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K42' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K43' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K44' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K45' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K46' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K47' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K48' GROUP BY k
        UNION ALL SELECT k, argMax((lc1, lc2, lc3, lc4, lc5, lc6, v), ts) FROM lc_many_marks_point_lookups WHERE k = 'K49' GROUP BY k
        FORMAT Null
        SETTINGS max_threads = 1
    