
        CREATE TABLE IF NOT EXISTS interpret_table_07
        (
            `idU128` UInt128,
            `idU128_2` UInt128,
            `idU128_3` UInt128,
            `nI16` Nullable(Int16) DEFAULT CAST(NULL, 'Nullable(Int16)'),
            `idColumnI64` Nullable(Int64) DEFAULT CAST(NULL, 'Nullable(Int64)'),
            `nStr` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_2` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nI16_02` Nullable(Int16) DEFAULT CAST(NULL, 'Nullable(Int16)'),
            `nStr_3` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_4` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_5` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nI8_01` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_02` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_03` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_04` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_05` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_06` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nDate_01` Nullable(Date) DEFAULT CAST(NULL, 'Nullable(Date)'),
            `nStr_6` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_7` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_8` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_9` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_10` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_11` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nI8_07` Nullable(UInt8) DEFAULT CAST(NULL, 'Nullable(UInt8)'),
            `nI8_08` Nullable(UInt8) DEFAULT CAST(NULL, 'Nullable(UInt8)'),
            `Str_01` String,
            `nI32_01` Nullable(Int32) DEFAULT CAST(NULL, 'Nullable(Int32)'),
            `nI8_19` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_09` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_10` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_11` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_12` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_13` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_14` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nStr_12` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nStr_13` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nI8_15` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_16` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nDateTime_01` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_02` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_03` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_04` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_05` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_06` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_07` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_08` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_09` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_10` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_11` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nDateTime_12` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nF64_01` Nullable(Float64) DEFAULT CAST(NULL, 'Nullable(Float64)'),
            `nStr_14` Nullable(String) DEFAULT CAST(NULL, 'Nullable(String)'),
            `nDate_02` Nullable(Date) DEFAULT CAST(NULL, 'Nullable(Date)'),
            `nDateTime_13` Nullable(DateTime) DEFAULT CAST(NULL, 'Nullable(DateTime)'),
            `nF64_02` Nullable(Float64) DEFAULT CAST(NULL, 'Nullable(Float64)'),
            `nF64_03` Nullable(Float64) DEFAULT CAST(NULL, 'Nullable(Float64)'),
            `nF64_04` Nullable(Float64) DEFAULT CAST(NULL, 'Nullable(Float64)'),
            `nF64_05` Nullable(Float64) DEFAULT CAST(NULL, 'Nullable(Float64)'),
            `nI8_18` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)'),
            `nI8_17` Nullable(Int8) DEFAULT CAST(NULL, 'Nullable(Int8)')
        )
        ENGINE = Join(ANY, LEFT, idU128);
    