
        CREATE TABLE IF NOT EXISTS interpret_table_01
        (
            `idColumnU64` UInt64,
            `dateColumn` DateTime,
            `aggCount` AggregateFunction(count),
            `aggArgMaxFloat32_1` AggregateFunction(argMax, Float32, DateTime),
            `aggArgMaxString` AggregateFunction(argMax, String, DateTime),
            `aggArgMaxFloat32_2` AggregateFunction(argMax, Float32, DateTime),
            `nDateTime_02_date` SimpleAggregateFunction(max, DateTime),
            `nDateTime_02_date_292929292` SimpleAggregateFunction(max, DateTime),
            `agg_topk_uint32` AggregateFunction(topKWeighted(2), UInt32, UInt32),
            `agg_argmax_string_datetime_01` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_u8_01` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_string_datetime_02` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_03` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_04` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_05` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_06` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_07` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_u8_02` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_string_u8_03` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_string_u8_04` AggregateFunction(argMax, UInt8, DateTime),
            `agg_count_01` AggregateFunction(count),
            `agg_count_02` AggregateFunction(count),
            `agg_count_03` AggregateFunction(count),
            `agg_count_04` AggregateFunction(count),
            `agg_count_05` AggregateFunction(count),
            `agg_count_06` AggregateFunction(count),
            `agg_count_07` AggregateFunction(count),
            `agg_count_08` AggregateFunction(count),
            `agg_count_09` AggregateFunction(count),
            `agg_count_10` AggregateFunction(count),
            `agg_count_11` AggregateFunction(count),
            `agg_count_12` AggregateFunction(count),
            `agg_count_13` AggregateFunction(count),
            `agg_count_14` AggregateFunction(count),
            `agg_count_15` AggregateFunction(count),
            `agg_count_16` AggregateFunction(count),
            `agg_argmax_string_datetime_08` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_f32_datetime_01` AggregateFunction(argMax, Float32, DateTime),
            `agg_argmax_string_datetime_09` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_f32_datetime_02` AggregateFunction(argMax, Float32, DateTime),
            `agg_argmax_date_datetime_01` AggregateFunction(argMax, Date, DateTime),
            `agg_argmax_date_datetime_02` AggregateFunction(argMax, Date, DateTime),
            `agg_argmax_u8_other_01` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_u8_other_02` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_u8_other_03` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_u8_other_04` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_string_datetime_10` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_u8_other_05` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_u8_other_06` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_u8_other_07` AggregateFunction(argMax, UInt8, DateTime),
            `agg_argmax_string_datetime_11` AggregateFunction(argMax, String, DateTime),
            `other_max_datetime_01` SimpleAggregateFunction(max, DateTime),
            `other_max_datetime_02` SimpleAggregateFunction(max, DateTime),
            `nDateTime_03_date` SimpleAggregateFunction(max, DateTime),
            `nDateTime_03_shown_date` SimpleAggregateFunction(max, DateTime),
            `nDateTime_04_date` SimpleAggregateFunction(max, DateTime),
            `nDateTime_04_shown_date` SimpleAggregateFunction(max, DateTime),
            `aggCount_3` AggregateFunction(count),
            `uniq_date_agg` AggregateFunction(uniq, Date),
            `aggCount_4` AggregateFunction(count),
            `agg_argmax_u128_datetime_01` AggregateFunction(argMax, UInt128, DateTime),
            `topk_u128_01` AggregateFunction(topKWeighted(5), UInt128, UInt32),
            `agg_argmax_string_datetime_12` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_13` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_14` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_datetime_15` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_u32_datetime_01` AggregateFunction(argMax, UInt32, DateTime),
            `agg_argmax_string_datetime_16` AggregateFunction(argMax, String, DateTime),
            `agg_argmax_string_u8_100` AggregateFunction(argMax, String, UInt8),
            `agg_argmax_string_datetime_18` AggregateFunction(argMax, String, DateTime),
            `other_max_datetime_05` SimpleAggregateFunction(max, DateTime),
            `topk_Datetime_u32_u32` AggregateFunction(topKWeighted(5), UInt32, UInt32),
            `agg_argmax_string_datetime_17` AggregateFunction(argMax, String, DateTime),
            `other_max_datetime_09` SimpleAggregateFunction(max, DateTime),
            `agg_count_17` AggregateFunction(count),
            `agg_count_18` AggregateFunction(count),
            `agg_count_19` AggregateFunction(count),
            `agg_count_20` AggregateFunction(count)
        )
        ENGINE = AggregatingMergeTree()
        PARTITION BY toYYYYMM(dateColumn)
        ORDER BY idColumnU64
        TTL dateColumn + toIntervalMonth(6)
        SETTINGS index_granularity = 1024, ttl_only_drop_parts = 1, min_rows_for_wide_part = 1000000000;
    