
        CREATE TABLE my_table
        (
            `id` String,
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_1` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_2` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_3` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_4` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_5` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_6` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_7` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_8` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_9` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_10` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_11` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_12` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_13` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_14` Nullable(String),
            `long_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_longlong_long_long_long_long_column_name_15` Nullable(String)
        )
        ENGINE = MergeTree
        ORDER BY id
    